### ISSUE TITLE
Issue with running Engarde patcher

### ISSUE THREAD

**Issue by skinjack** [theSkyseS/Engarde-Synthesis-Patcher#31]
I'm not really sure what is needed to report this. When I run it I get this error:

Compiling
Extra data folder already exists. Leaving as is: E:\Utilities\Synthesis\Data\Engarde-Synthesis-Patcher
(C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Git\kpvfe0ke.nyy\Runner\Engarde_Synthesis): dotnet build --runtime win-x64 "Engarde_Synthesis.csproj" -c Release
Compiled
Sha 767b178569fbd658239e656c117d9f9fd3712914
(): dotnet run --project "C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Git\kpvfe0ke.nyy\Runner\Engarde_Synthesis\Engarde_Synthesis.csproj" -c Release --runtime win-x64 --no-build check-runnability --DataFolderPath "E:\STEAM\steamapps\common\Skyrim Special Edition\Data" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Workspace\Plugins.txt
Running
(): dotnet run --project "C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Git\kpvfe0ke.nyy\Runner\Engarde_Synthesis\Engarde_Synthesis.csproj" --runtime win-x64 --no-build -c Release run-patcher --DataFolderPath "E:\STEAM\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder E:\Utilities\Synthesis\Data\Engarde-Synthesis-Patcher --DefaultDataFolderPath C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Git\kpvfe0ke.nyy\Runner\Engarde_Synthesis\Data --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Workspace\Plugins.txt --OutputPath "C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Workspace\0 - Engarde-Synthesis-Patcher" --PatcherName Engarde-Synthesis-Patcher --PersistencePath C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Persistence
Mutagen version: 0.30.3
Mutagen sha: d7118b3a322a7a14999b167d4ce8452e6ab551f6
Synthesis version: 0.19.1
Synthesis sha: ab5cb49494aaeccce624b480564f8627e58ef9bc
run-patcher --DataFolderPath "E:\STEAM\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder E:\Utilities\Synthesis\Data\Engarde-Synthesis-Patcher --DefaultDataFolderPath C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Git\kpvfe0ke.nyy\Runner\Engarde_Synthesis\Data --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Workspace\Plugins.txt --OutputPath "C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Workspace\0 - Engarde-Synthesis-Patcher" --PatcherName Engarde-Synthesis-Patcher --PersistencePath C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Persistence
Checking runnability
Checking runnability complete
Prepping state.
Using TextFileSharedFormKeyAllocator allocator
Reading settings: E:\Utilities\Synthesis\Data\Engarde-Synthesis-Patcher\settings.json
System.NullReferenceException: Object reference not set to an instance of an object.
   at Engarde_Synthesis.Program.ChangeWeapon(IWeapon weaponCopy, Int32 defaultWeight, Single damageMult, Single reachMult, Single speedMult, Single critMult, Single staggerMult, WeaponCritChance critChance, WeaponArmorPenetration armorPenetration) in C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Git\kpvfe0ke.nyy\Runner\Engarde_Synthesis\Program.cs:line 161
   at Engarde_Synthesis.Program.PatchWeapons(IPatcherState`2 state) in C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Git\kpvfe0ke.nyy\Runner\Engarde_Synthesis\Program.cs:line 704
   at Engarde_Synthesis.Program.RunPatch(IPatcherState`2 state) in C:\Users\Bruce\AppData\Local\Temp\Synthesis\tpkjgiz3.41v\Git\kpvfe0ke.nyy\Runner\Engarde_Synthesis\Program.cs:line 2742
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 93
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 455
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 403
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 377
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

I'm not sure what to do with this error, but my guess is it has to do something with either Growl, Savage Skyrim, or Enderal as those mods came up in a previous error. This was corrected updating Synthesis to 19.1 but I'm still getting an error. I do apologize if I'm not following an established format or etiquette. Newbs. :)

**Comment by skinjack** [comment]
This seems to have been fixed with the latest version, so thank you for responding so quickly.
