### ISSUE TITLE
Patcher Error: NPC without a Race

### ISSUE THREAD

**Issue by Heartbreaker714** [theSkyseS/Engarde-Synthesis-Patcher#32]
I've been having an issue with the patcher. Over on the Synthesis discord I got some insight that it's "looking like it's an issue with Engarde's code. There's an NPC that doesn't have a race that it's not liking" I've attached [a picture](https://cdn.discordapp.com/attachments/759336600441454602/856002692606459904/Engarde_Error.JPG) of the error message and will paste the test from the message:
<details>
Compiling
Extra data folder already exists. Leaving as is: C:\Games\Phoenix Flavour\tools\Synthesis\Data\Engarde-Synthesis-Patcher
(C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Git\5jgkkptd.as0\Runner\Engarde_Synthesis): dotnet build --runtime win-x64 "Engarde_Synthesis.csproj" -c Release
Compiled
Sha d52383374d09c2841bfe0bfab0c7cff2bb52d8f7
(): dotnet run --project "C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Git\5jgkkptd.as0\Runner\Engarde_Synthesis\Engarde_Synthesis.csproj" -c Release --runtime win-x64 --no-build check-runnability --DataFolderPath "C:\Games\STEAM\steamapps\common\Skyrim Special Edition\Data" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Workspace\Plugins.txt
Running
(): dotnet run --project "C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Git\5jgkkptd.as0\Runner\Engarde_Synthesis\Engarde_Synthesis.csproj" --runtime win-x64 --no-build -c Release run-patcher --DataFolderPath "C:\Games\STEAM\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "C:\Games\Phoenix Flavour\tools\Synthesis\Data\Engarde-Synthesis-Patcher" --DefaultDataFolderPath C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Git\5jgkkptd.as0\Runner\Engarde_Synthesis\Data --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Workspace\Plugins.txt --OutputPath "C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Workspace\0 - Engarde-Synthesis-Patcher" --PatcherName Engarde-Synthesis-Patcher --PersistencePath C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Persistence
Mutagen version: 0.30.5
Mutagen sha: 4ccd774986fd8f646dcc981c97e2f01d1432b00d
Synthesis version: 0.19.2
Synthesis sha: cdf4551d49c580ac024e64e653204e3c20fb6e96
run-patcher --DataFolderPath "C:\Games\STEAM\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "C:\Games\Phoenix Flavour\tools\Synthesis\Data\Engarde-Synthesis-Patcher" --DefaultDataFolderPath C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Git\5jgkkptd.as0\Runner\Engarde_Synthesis\Data --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Workspace\Plugins.txt --OutputPath "C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Workspace\0 - Engarde-Synthesis-Patcher" --PatcherName Engarde-Synthesis-Patcher --PersistencePath C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Persistence
Checking runnability
Checking runnability complete
Prepping state.
Using TextFileSharedFormKeyAllocator allocator
Reading settings: C:\Games\Phoenix Flavour\tools\Synthesis\Data\Engarde-Synthesis-Patcher\settings.json
System.AggregateException: One or more errors occurred. (Could not resolve record)
 ---> RecordException Null => Null<Race>: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
   at Engarde_Synthesis.Program.<>c__DisplayClass22_0.<PatchNpcs>g__Predicate|0(INpcGetter npc) in C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Git\5jgkkptd.as0\Runner\Engarde_Synthesis\Program.cs:line 781
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at Engarde_Synthesis.Program.PatchNpcs(IPatcherState`2 state)
   at Engarde_Synthesis.Program.RunPatch(IPatcherState`2 state) in C:\Users\Administrator\AppData\Local\Temp\Synthesis\vmjjbzal.w5b\Git\5jgkkptd.as0\Runner\Engarde_Synthesis\Program.cs:line 2755
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 93
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 455
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 403
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 377
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)
</details>

**Comment by theSkyseS** [comment]
db15c59
